### ISSUE TITLE
Using () in Holidays-Titles will generate not working flowcharts

### ISSUE THREAD

**Issue by webflash-aj** [mozziemozz/M365CallFlowVisualizer#23]
Using () in the Title/Description of Holidays, will generate not working flowcharts markdown-code.

So "(" and ")" has to be removed prior.

**Comment by mozziemozz** [comment]
Hi, I fixed that in Version 2.7.0 by reusing the Function FixDisplayName which was written by @ChocoMilkWithoutSugar .
All brackets and square brackets will be removed from the names before it's written into markdown.

**Comment by webflash-aj** [comment]
Dear Martin

It's still not working, if you have "(" or ")" in the Name of an auto-attendant.
Just tried Version 2.7.1. The brackets will still not be removed.

When I remove the brackets in the name of the auto-attendant, it's working fine.

Andy

**Comment by webflash-aj** [comment]
@mozziemozz 
I know that i haven't mentioned the AA. Just tried again and noticed that the diagram is still not working.
For me it's fine, just removed the brackets from the name and it's working now as expected.
Maybe you want to reopen the issue? Unfortunately I can't!

**Comment by mozziemozz** [comment]
Yes, because these are part of Mermaid Syntax. Sorry I generally try to avoid to use special characters apart from hyphens or underscores when naming things, hence I never tested it. Pipes (|) are also not supported. I'll need to check if it's possible to escape these chars in mermaid.

**Comment by sjackson0109** [comment]
Perhaps perform some normalisation regex?
EG:
``` < becomes &lt ```
or
``` { becomes &#40; ```

**Comment by sjackson0109** [comment]
works in the .html file and mermaid.live diagram
